# Central Role for Split
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# Enable Bluetooth controller (required for zmk-feature-split-esb)
CONFIG_BT=y

# General Keyboard Settings
CONFIG_ZMK_KEYBOARD_NAME="esbDabase"
CONFIG_ZMK_USB=y

CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y
CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=10
CONFIG_ZMK_HID_CONSUMER_REPORT_SIZE=10
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y

CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_PM_SOFT_OFF=n
