CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_BT_MAX_PAIRED=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_PM_SOFT_OFF=n
CONFIG_ZMK_STUDIO=y

# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
# No battery, only USB
CONFIG_ZMK_BATTERY_REPORTING=n
